apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx:1.25.0-alpine
          ports:
            - containerPort: 80
